#!/usr/bin/env node

var program = require('commander'),
    init = require('./lib/init'),
    login = require('./lib/login');

program.version('0.0.1')
  .option('-j, --json', 'Output in JSON format')
  .parse(process.argv);

init(program, function(config) {
  function wrap(callback) {
    return function(err, resp, data) {
      return err
        ? console.error(err)
        : callback(resp, data);
    };
  }

  var client = login(config);
  client.contacts('get', wrap(print));
});

function print(resp, data) {
  if(!data || !data.contacts) {
    return;
  }


  if(program.json) {
    console.log(JSON.stringify(data.contacts));
    return;
  }

  var contacts = Object.keys(data.contacts).map(function(key) {
      return data.contacts[key];
    })
    .sort(function(a, b) {
      var c = a.name[0] || 'z',
          d = b.name[0] || 'z';

      return c > d;
    });

  contacts.forEach(function(c) {
    var name = c.name,
        phone = c.phoneNumber.replace('+', '');

    console.log(name + '\t' + phone);

  });
}
