#!/usr/bin/env node

var program = require('commander'),
    voicejs = require('voice.js'),
    init = require('./lib/init'),
    login = require('./lib/login'),
    pipe = require('./lib/pipe');

program.version('0.1.0')
  .option('-p, --person', 'The person to send the message to.')
  .option('-n, --number', 'The number to send the message to.')
  .parse(process.argv);

init(program, function(config) {
  pipe(function(phoneNumbers) {
    var message = program.args.join(' ');

    loginAndSend(config, phoneNumbers[0], message);
  });

  if(program.number) {
    var number = program.args[0];
    var message = program.args.slice(1).join(' ');
    loginAndSend(config, number, message);
  }
});

function loginAndSend(config, number, message) {
  var client = login(config);

  send(client, number, message);
}

function wrapped(callback, errback) {
  return function(err, resp, data) {
    if(err) {
      (errback || function(){})(err);
    } else {
      callback(resp, data);
    }
  };
}

function send(client, number, message) {
  client.sms({
    to: number,
    text: message
  }, wrapped(function onSuccess() {
      console.log(number + ': ' + message);
      process.exit();
    }, function onError(err) {
      console.error(err);
    })
  );
}
